### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by marksev1** [alinleonard/LCD-I2C-Raspberry-Pi-2#1]
If I understand correctly here each line in the display has to be separately filled with text. What about if I have a big amount of text, for example here: http://meteo.arso.gov.si/uploads/probase/www/fproduct/text/sl/fcast_si_text.html if I would want to print all the text under "Napoved za Slovenijo", how would I achieve that? Since I already have a python script which prints all the text from there and I would really like to display it on 20x4 display. Probably all of it wouldn't fit so how would I do the scrolling?

Hopefully you can help me!

**Comment by alinleonard** [comment]
I just saw your question, did you resolve your issue?

**Comment by marksev1** [comment]
Nah haven't yet... I have the script that scraps the text from that weather forecast html page and prints it into the terminal, but dunno how I would continue with displaying all of that on the lcd screen.

**Comment by alinleonard** [comment]
you don't know how to scroll the text to view on lcd?
Did you look at [test_lcd.py](https://github.com/alinleonard/LCD-I2C-Raspberry-Pi-2/blob/master/test_lcd.py) ?

**Comment by marksev1** [comment]
Does this code care about length of text, because the length of forecast from which i scrap the text is variable.

**Comment by alinleonard** [comment]
Depends how you get the text, any \n \r \t would mess up the display . What I would try to do, if the text you get is clean, I would use lcd.message(fetched_text) , then I would use
for i in range(0, fetched.len())
 lcd.scrollDisplayLeft()
 time.sleep(0.5)

**Comment by alinleonard** [comment]
or you could just create a function were it will get the max amount you can display on lcd , trim the text display it , sleep, clean lcd, then display the text+offset  and so on.

**Comment by marksev1** [comment]
Thanks this is going to help me! :)
